apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: fleet
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/mhausenblas/kcf/releases/download/v0.1.0/fleet_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./fleet"
      to: "."
    bin: "fleet"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/mhausenblas/kcf/releases/download/v0.1.0/fleet_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./fleet"
      to: "."
    bin: "fleet"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/mhausenblas/kcf/releases/download/v0.1.0/fleet_windows_amd64.zip
    sha256: ""
    files:
    - from: "/fleet.exe"
      to: "."
    bin: "fleet.exe"
  shortDescription: A new plugin
  homepage: https://github.com/mhausenblas/kcf
  caveats: |
    Usage:
      $ kubectl fleet

    For additional options:
      $ kubectl fleet --help
      or https://github.com/mhausenblas/kcf/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
